### ISSUE TITLE
Jumping against object causes continuous upward motion

### ISSUE THREAD

**Issue by DGriffin91** [qhdwight/bevy_fps_controller#2]
Jumping while pressing player capsule against object results in continuous upward motion

https://user-images.githubusercontent.com/33357138/183527719-06085c54-c707-45b8-9f02-2959100dd561.mp4

**Comment by qhdwight** [comment]
Unintended wall climb mechanic???? Jk will look into

**Comment by DGriffin91** [comment]
I was thinking that too, might be worth noting what caused the bug to possibly use later intentionally.

**Comment by rafaeldelboni** [comment]
I was playing around with this issue and this is happening because you casting a capsule to check if the player is on the floor, but you are orienting the rotation of the capsule casted as the camera pitch and yaw.
```rust
        let orientation = look_quat(input.pitch, input.yaw);
...
let ground_hit = physics_context
    .cast_shape(
        position,
        orientation, // here
        cast_velocity,
        &cast_capsule,
        max_distance,
        groups,
    )
    .map(|(_handle, hit)| hit);
```
If you replace orientation with the player rotation `transform.rotation` should solve the wall climbing.

Another thing I would do is calculate gravity in every loop and not only when the player is jumping.
`end_velocity.y -= controller.gravity * dt;`

If you want I can open a PR with the fix.

**Comment by rafaeldelboni** [comment]
Btw @DGriffin91 I loved your game [subfuse](https://github.com/DGriffin91/BevyJam2022-2), using the source as my main bevy source of study! Please keep up the good work.

**Comment by qhdwight** [comment]
Hi @rafaeldelboni , thank you for your comment. Feel free to open a PR and I can check it out.

The gravity issue sounds like a separate issue/PR. Why calculate gravity even when the player is grounded? You know it shouldn't affect their velocity until you no longer have ground underneath you.

**Comment by rafaeldelboni** [comment]
Nice point, I got some cases while jumping towards a wall (haha never thought I would write this sentence) that the ground_hit was triggering, but I was colliding against the wall and not the floor, that would cause a sticky wall effect, while not climbing I could stay there floating forever :)

But you right, that another topic.
