### ISSUE TITLE
multiplayer?

### ISSUE THREAD

**Issue by duckfromdiscord** [qhdwight/bevy_fps_controller#21]
is it possible to get this to work as a multiplayer game?

i just tried that example and it runs beautifully. i really like it 😄, very well done. it's fluid, it ran on the first compile, and the movement worked quite well. just wanted to say it's awesome.

**Comment by qhdwight** [comment]
I haven't tried anything multiplayer in Bevy yet so I can't really say too much. I think the underlying problem is you have to find a framework that does client side prediction + reconciliation and then integrate that with Bevy Rapier (which is what this uses under the hood). Then this package can run on top of that and it is abstracted away.

Also thank you for your kind words! Glad you enjoyed it.

**Comment by duckfromdiscord** [comment]
Sounds good. I will have to do a lot of learning about multiplayer code
